export const defaultSiteSettings = {
  'store.name': 'Entix Jewellery',
  'store.legalName': 'Entix Jewellery',
  'store.email': 'care@entix.jewellery',
  'store.phone': '',
  'store.country': 'India',
  'store.currency': 'INR',
  'store.orderPrefix': 'ENT',
  'store.address': '',
  'store.city': '',
  'store.state': '',
  'store.postalCode': '',
  'store.businessProfile': 'Fine jewellery for modern rituals.',
  'domain.primary': 'https://entix-jewellery.vercel.app',
  'domain.canonical': 'https://entix-jewellery.vercel.app',
  'domain.redirects': 'www to apex, http to https',
  'payment.codLimit': '100000',
  'payment.captureMode': 'automatic',
  'payment.refundWindow': '7',
  'seo.homeTitle': 'Entix - Fine Jewellery for Modern Rituals',
  'seo.homeDescription': 'Shop sculptural jewellery, ceremonial bangles, luminous rings, and refined gifting pieces by Entix.',
  'seo.ogImage': '',
  'seo.indexing': 'enabled',
  'seo.defaultProductTitle': '{product} | Entix Jewellery',
  'policy.return': 'Returns and exchanges are reviewed within 7 days of delivery for unworn pieces in original packaging.',
  'policy.shipping': 'Orders are packed with care and dispatched with tracked shipping across India.',
  'policy.privacy': 'Customer data is used only for account, order, fulfilment, and communication workflows.',
  'policy.terms': 'All orders are subject to availability, payment confirmation, and final quality checks.',
  'shipping.origin': 'India',
  'shipping.courier': 'Manual / Shiprocket ready',
  'shipping.freeAbove': '10000',
  'shipping.standardRate': '0',
  'shipping.expressRate': '299',
  'shipping.standardEta': '4-7 business days',
  'shipping.expressEta': '2-4 business days',
  'shipping.packageNote': 'Signature jewellery box with protective outer packaging.',
  'tax.gstin': '',
  'tax.invoicePrefix': 'ENT',
  'tax.displayMode': 'inclusive',
  'tax.defaultHsn': '7113',
  'tax.defaultPercent': '3',
  'notifications.fromName': 'Entix Jewellery',
  'notifications.fromEmail': 'concierge@entix.jewellery',
  'notifications.staffEmail': '',
  'notifications.orderSummary': 'enabled',
  'notifications.abandonedCart': 'enabled',
  'users.sessionHours': '24',
  'users.mfaStatus': 'planned',
  'users.invitePolicy': 'Owner approval required',
};

export type SettingKey = keyof typeof defaultSiteSettings;

export const settingKeys = Object.keys(defaultSiteSettings) as SettingKey[];
